### PR TITLE
Fixed AV occurs on change component while editing some property

### PR DESCRIPTION
**Pull request by benok**
Hi, I added additional quick fix for [the AV problem you wrote](https://github.com/MahdiSafsafi/zcontrols/pull/12#issuecomment-300127663
) before.

I can confirm the problem with [madExcept](http://www.madshi.net/madExceptDescription.htm) with[ "instantly crash on buffer overrun" option](http://help.madshi.net/madExceptSettings1.htm).
(Without madExcept with this option, whether AV occurs or not depends on the contents of the current memory. That's why I can't reproduce the AV before.)

Without this patch, UpdateButton is called before SetPropItem is called.
(You can see FPropItem has invalid address below)
"call stack"

This patch may not be best solution to fix the problem, but It seems to work :-)

### CODE REVIEW

**Comment by MahdiSafsafi** [comment]
I thought that the bug was fixed in the latest commit ?

**Comment by benok** [comment]
Hmm, could you try [madExcept](http://www.madshi.net/madExceptDescription.htm) with[ "instantly crash on buffer overrun" option](http://help.madshi.net/madExceptSettings1.htm) ? 
Without this, the sample program runs without error.

But checking with madExcpet and the above option, Access Violation occurs 100%.
Please check the order of the above handlers I wrote called.
I think you will find this patch or other additional logic is required to fix the AV.

p.s.
madExcept is very informative for every Delphi developers.
I used madExcept  several years to collect the call stack of the occurred exception on the user's environment.
But I didn't notice the power of "instantly crush on buffer overrun" option until last month.
With the aid of this option, I could fix some rarely happened and head aching Access Violation problem from our developing product.

**Comment by benok** [comment]
I found this patch cause another Access Violation.
I should have tested more before sending this PR.
I will try to fix, sorry.

**Comment by benok** [comment]
> I found this patch cause another Access Violation.

The above AV was caused by wrong dcu library path (of release build) and not caused by this patch.
I'll keep testing, with my current project,  but I reopen this PR.
Sorry to bother you again.

**Comment by MahdiSafsafi** [comment]
Please don't say sorry. This is an open source project. You're welcome to submit path, report bugs,etc...
Please keep testing your changes. Once it's safe, let me know and I'll take control from there.

**Comment by benok** [comment]
I'm sorry I forgot replying this.
I'm using zObjInspector with this patch in my app about several months, but I've never seen Access Violation any more.
So I think it's OK.  It is quite stable. (at least in my App)

**Comment by MahdiSafsafi** [comment]
Hi again, 
@pyscripter made a great patch (he added DPI support and made some good improvements). 
Please can you say whether the new commit fixes this bug or not (as I'm unable to reproduce it). If it does that's good. If not, I'm afraid that we need to reintegrate your patch manually (since the current patch is far ahead from this PR).

Regards,
Mahdi.

**Comment by benok** [comment]
Hi,
I merged recent changes by @pyscripter from MahdiSafsafi:master and confirmed my patch works without any problem.

I also confirmed this works on 10.2 Tokyo update 2, as well as 10 Seattle update 1.
I was a bit busy until recently, and finally upgraded to 10.2.

**Pull request merged**
